export const ADD_CARD_START = 'ADD_CARD_START';
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';
export const ADD_CARD_FAILURE = 'ADD_CARD_FAILURE';

export const GET_CARDS_LIST_START = 'GET_CARDS_LIST_START';
export const GET_CARDS_LIST_SUCCESS = 'GET_CARDS_LIST_SUCCESS';
export const GET_CARDS_LIST_FAILURE = 'GET_CARDS_LIST_FAILURE';

export const REMOVE_CARD_START = 'REMOVE_CARD_START';
export const REMOVE_CARD_SUCCESS = 'REMOVE_CARD_SUCCESS';
export const REMOVE_CARD_FAILURE = 'REMOVE_CARD_FAILURE';
