export const BID_PLACED_START = 'BID_PLACED_START';
export const BID_PLACED_SUCCESS = 'BID_PLACED_SUCCESS';
export const BID_PLACED_FAILURE = 'BID_PLACED_FAILURE';

export const BID_MATCHED_START = 'BID_MATCHED_START';
export const BID_MATCHED_SUCCESS = 'BID_MATCHED_SUCCESS';
export const BID_MATCHED_FAILURE = 'BID_MATCHED_FAILURE';

export const JOB_DETAILS_START = 'JOB_DETAILS_START';
export const JOB_DETAILS_SUCCESS = 'JOB_DETAILS_SUCCESS';
export const JOB_DETAILS_FAILURE = 'JOB_DETAILS_FAILURE';

export const MAKE_PAYMENT_START = 'MAKE_PAYMENT_START';
export const MAKE_PAYMENT_SUCCESS = 'MAKE_PAYMENT_SUCCESS';
export const MAKE_PAYMENT_FAILURE = 'MAKE_PAYMENT_FAILURE';

export const RATE_START = 'RATE_START';
export const RATE_SUCCESS = 'RATE_SUCCESS';
export const RATE_FAILURE = 'RATE_FAILURE';

export const BID_PLACED_STATUS = 'BID_PLACED_STATUS';
export const BID_MATCHED_STATUS = 'BID_MATCHED_STATUS';
