export const GET_IN_PROCESS_DISPUTE_LIST_START = 'GET_IN_PROCESS_DISPUTE_LIST_START';
export const GET_IN_PROCESS_DISPUTE_LIST_SUCCESS = 'GET_IN_PROCESS_DISPUTE_LIST_SUCCESS';
export const GET_IN_PROCESS_DISPUTE_LIST_FAILURE = 'GET_IN_PROCESS_DISPUTE_LIST_FAILURE';

export const REFRESH_IN_PROCESS_DISPUTE_LIST_START = 'REFRESH_IN_PROCESS_DISPUTE_LIST_START';

export const GET_COMPLETE_DISPUTE_LIST_START = 'GET_COMPLETE_DISPUTE_LIST_START';
export const GET_COMPLETE_DISPUTE_LIST_SUCCESS = 'GET_COMPLETE_DISPUTE_LIST_SUCCESS';
export const GET_COMPLETE_DISPUTE_LIST_FAILURE = 'GET_COMPLETE_DISPUTE_LIST_FAILURE';

export const REFRESH_COMPLETE_DISPUTE_LIST_START = 'REFRESH_COMPLETE_DISPUTE_LIST_START';

export const DISPUTE_ORDER_START = 'DISPUTE_ORDER_START';
export const DISPUTE_ORDER_SUCCESS = 'DISPUTE_ORDER_SUCCESS';
export const DISPUTE_ORDER_FAILURE = 'DISPUTE_ORDER_FAILURE';

export const REPLY_DISPUTE_START = 'REPLY_DISPUTE_START';
export const REPLY_DISPUTE_SUCCESS = 'REPLY_DISPUTE_SUCCESS';
export const REPLY_DISPUTE_FAILURE = 'REPLY_DISPUTE_FAILURE';