export const CURRENT_LOCATION = 'CURRENT_LOCATION';

export const GET_REQUEST_LIST_START = 'GET_REQUEST_LIST_START';
export const GET_REQUEST_LIST_SUCCESS = 'GET_REQUEST_LIST_SUCCESS';
export const GET_REQUEST_LIST_FAILURE = 'GET_REQUEST_LIST_FAILURE';

export const PLACE_BID_START = 'PLACE_BID_START';
export const PLACE_BID_SUCCESS = 'PLACE_BID_SUCCESS';
export const PLACE_BID_FAILURE = 'PLACE_BID_FAILURE';

export const ADMIN_DATA_START = 'ADMIN_DATA_START';
export const ADMIN_DATA_SUCCESS = 'ADMIN_DATA_SUCCESS';
export const ADMIN_DATA_FAILURE = 'ADMIN_DATA_FAILURE';

export const REQUEST_DETAILS_START = 'REQUEST_DETAILS_START';
export const REQUEST_DETAILS_SUCCESS = 'REQUEST_DETAILS_SUCCESS';
export const REQUEST_DETAILS_FAILURE = 'REQUEST_DETAILS_FAILURE';