export const GET_IN_PROCESS_LIST_START = 'GET_IN_PROCESS_LIST_START';
export const GET_IN_PROCESS_LIST_SUCCESS = 'GET_IN_PROCESS_LIST_SUCCESS';
export const GET_IN_PROCESS_LIST_FAILURE = 'GET_IN_PROCESS_LIST_FAILURE';

export const REFRESH_IN_PROCESS_LIST_START = 'REFRESH_IN_PROCESS_LIST_START';

export const GET_COMPLETE_LIST_START = 'GET_COMPLETE_LIST_START';
export const GET_COMPLETE_LIST_SUCCESS = 'GET_COMPLETE_LIST_SUCCESS';
export const GET_COMPLETE_LIST_FAILURE = 'GET_COMPLETE_LIST_FAILURE';

export const REFRESH_COMPLETE_LIST_START = 'REFRESH_COMPLETE_LIST_START';

export const CANCEL_ORDER_START = 'CANCEL_ORDER_START';
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS';
export const CANCEL_ORDER_FAILURE = 'CANCEL_ORDER_FAILURE';

export const SUBMIT_REVIEW_START = 'SUBMIT_REVIEW_START';
export const SUBMIT_REVIEW_SUCCESS = 'SUBMIT_REVIEW_SUCCESS';
export const SUBMIT_REVIEW_FAILURESS = 'SUBMIT_REVIEW_FAILURE';
